class Entity {
  Number wealth
  Number pSatisfaction
  Object goals
}
class Individual {
  Bool isEmployed
  Number pMotivation
  Skill skill
}
class Citizen
class Immigrant
class State {
  Number population
  Number foodStores
}

Entity *-- Citizen
Individual *-- Citizen
Entity *-- Immigrant
Individual *-- Immigrant
Entity *-- State
Citizen o-- State
Immigrant o-- State
