class Entity {
  Double wealth
  Int satisfaction
  Goal[] goals
}
class Individual {
  bool isEmployed
  Int motivation
  Int hunger
  Skill[] skills
}
class Citizen
class Immigrant
class State {
  Long population
  Long foodStores
}

Entity *-- Citizen
Individual *-- Citizen
Entity *-- Immigrant
Individual *-- Immigrant
Entity *-- State
Citizen o-- State
Immigrant o-- State
